"""initial schema - 8 tables

Revision ID: 3608997bbfce
Revises: 
Create Date: 2026-04-06 22:12:17.632331
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3608997bbfce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AGENT_M',
    sa.Column('RGST_DTM', sa.DateTime(), nullable=False),
    sa.Column('RGST_ID', sa.String(length=20), nullable=False),
    sa.Column('UPD_DTM', sa.DateTime(), nullable=False),
    sa.Column('UPPR_ID', sa.String(length=20), nullable=False),
    sa.Column('AGENT_ID', sa.String(length=50), nullable=False),
    sa.Column('AGENT_SEQ', sa.Numeric(precision=10), nullable=False),
    sa.Column('AGENT_NM', sa.String(length=100), nullable=False),
    sa.Column('AGENT_FRWK_NM', sa.String(length=100), nullable=False),
    sa.Column('AGENT_PATH_ADDR', sa.String(length=300), nullable=False),
    sa.Column('AGENT_DSCR_CNTT', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('USE_YN', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('AGENT_ID', 'AGENT_SEQ')
    )
    op.create_table('AGENT_MEM_USE_N',
    sa.Column('RGST_DTM', sa.DateTime(), nullable=False),
    sa.Column('RGST_ID', sa.String(length=20), nullable=False),
    sa.Column('UPD_DTM', sa.DateTime(), nullable=False),
    sa.Column('UPPR_ID', sa.String(length=20), nullable=False),
    sa.Column('AGENT_ID', sa.String(length=100), nullable=False),
    sa.Column('AGENT_SEQ', sa.Numeric(precision=10), nullable=False),
    sa.Column('EMP_NO', sa.String(length=100), nullable=False),
    sa.Column('AGENT_MEM_PATH_ADDR', sa.String(length=300), nullable=True),
    sa.Column('AGENT_TYPE_DSCR_CNTT', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=False),
    sa.Column('USE_YN', sa.String(length=1), nullable=False),
    sa.Column('LAST_SYNC_DTM', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('AGENT_ID', 'AGENT_SEQ', 'EMP_NO')
    )
    op.create_table('ATCH_FILE_M',
    sa.Column('RGST_DTM', sa.DateTime(), nullable=False),
    sa.Column('RGST_ID', sa.String(length=20), nullable=False),
    sa.Column('UPD_DTM', sa.DateTime(), nullable=False),
    sa.Column('UPPR_ID', sa.String(length=20), nullable=False),
    sa.Column('CHTB_TLK_ID', sa.String(length=50), nullable=False),
    sa.Column('ATCH_FILE_NO', sa.BigInteger(), nullable=False),
    sa.Column('ATCH_FILE_NM', sa.String(length=255), nullable=True),
    sa.Column('ATCH_FILE_URL_ADDR', sa.String(length=500), nullable=True),
    sa.Column('ATCH_TOKN_ECNT', sa.Numeric(precision=10), nullable=True),
    sa.PrimaryKeyConstraint('CHTB_TLK_ID', 'ATCH_FILE_NO')
    )
    op.create_table('CHTB_MSG_D',
    sa.Column('RGST_DTM', sa.DateTime(), nullable=False),
    sa.Column('RGST_ID', sa.String(length=20), nullable=False),
    sa.Column('UPD_DTM', sa.DateTime(), nullable=False),
    sa.Column('UPPR_ID', sa.String(length=20), nullable=False),
    sa.Column('CHTB_TLK_SMRY_ID', sa.String(length=50), nullable=False),
    sa.Column('CHTB_TLK_ID', sa.String(length=50), nullable=False),
    sa.Column('CHTB_TLK_SEQ', sa.Numeric(precision=10), nullable=False),
    sa.Column('AGNT_ID', sa.String(length=50), nullable=True),
    sa.Column('MSG_ROLE_NM', sa.String(length=50), nullable=True),
    sa.Column('CHTB_MSG_CNTT', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True),
    sa.Column('CHTB_MDL_NM', sa.String(length=100), nullable=True),
    sa.Column('CHTB_OFFR_MDL_NM', sa.String(length=50), nullable=True),
    sa.Column('CHTB_INPUT_TOKN_ECNT', sa.Numeric(precision=10), nullable=True),
    sa.Column('CHTB_OUTPUT_TOKN_ECNT', sa.Numeric(precision=10), nullable=True),
    sa.Column('CHTB_TOT_TOKN_ECNT', sa.Numeric(precision=10), nullable=True),
    sa.Column('RPLY_TIME', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ATCH_FILE_NO', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('CHTB_TLK_SMRY_ID', 'CHTB_TLK_ID', 'CHTB_TLK_SEQ')
    )
    op.create_table('CHTB_SMRY_D',
    sa.Column('RGST_DTM', sa.DateTime(), nullable=False),
    sa.Column('RGST_ID', sa.String(length=20), nullable=False),
    sa.Column('UPD_DTM', sa.DateTime(), nullable=False),
    sa.Column('UPPR_ID', sa.String(length=20), nullable=False),
    sa.Column('CHTB_TLK_SMRY_ID', sa.String(length=50), nullable=False),
    sa.Column('EMP_NO', sa.String(length=20), nullable=False),
    sa.Column('CHTB_TLK_SMRY_TTL', sa.String(length=255), nullable=True),
    sa.Column('CHTB_MDL_NM', sa.String(length=100), nullable=True),
    sa.Column('BKMR_YN', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('CHTB_TLK_SMRY_ID')
    )
    op.create_table('CRTF_TOKN_N',
    sa.Column('RGST_DTM', sa.DateTime(), nullable=False),
    sa.Column('RGST_ID', sa.String(length=20), nullable=False),
    sa.Column('UPD_DTM', sa.DateTime(), nullable=False),
    sa.Column('UPPR_ID', sa.String(length=20), nullable=False),
    sa.Column('EMP_NO', sa.String(length=15), nullable=False),
    sa.Column('CRTF_TOKN_ID', sa.String(length=50), nullable=False),
    sa.Column('CRTF_TOKN_ECR_CNTT', sa.String(length=300), nullable=False),
    sa.Column('DISS_YN', sa.String(length=1), nullable=True),
    sa.Column('TRTN_DTM', sa.DateTime(), nullable=True),
    sa.Column('DISS_DTM', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('EMP_NO', 'CRTF_TOKN_ID')
    )
    op.create_table('DEPT_M',
    sa.Column('RGST_DTM', sa.DateTime(), nullable=False),
    sa.Column('RGST_ID', sa.String(length=20), nullable=False),
    sa.Column('UPD_DTM', sa.DateTime(), nullable=False),
    sa.Column('UPPR_ID', sa.String(length=20), nullable=False),
    sa.Column('DEPT_CD', sa.String(length=8), nullable=False),
    sa.Column('DEPT_NM', sa.String(length=50), nullable=True),
    sa.Column('DD_TOKN_ECNT', sa.Numeric(precision=10), nullable=True),
    sa.Column('MM_TOKN_ECNT', sa.Numeric(precision=10), nullable=True),
    sa.Column('ACES_MDL_CNTT', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('DEPT_CD'),
    sa.UniqueConstraint('DEPT_NM')
    )
    op.create_table('EMP_M',
    sa.Column('RGST_DTM', sa.DateTime(), nullable=False),
    sa.Column('RGST_ID', sa.String(length=20), nullable=False),
    sa.Column('UPD_DTM', sa.DateTime(), nullable=False),
    sa.Column('UPPR_ID', sa.String(length=20), nullable=False),
    sa.Column('EMP_NO', sa.String(length=15), nullable=False),
    sa.Column('USER_NM', sa.String(length=50), nullable=True),
    sa.Column('EML_ADDR', sa.String(length=100), nullable=True),
    sa.Column('ECR_PWD', sa.String(length=255), nullable=True),
    sa.Column('USER_ROLE_NM', sa.String(length=50), nullable=False),
    sa.Column('PSTN_DEPT_CD', sa.String(length=8), nullable=False),
    sa.Column('ACNT_STS_NM', sa.String(length=50), nullable=False),
    sa.Column('LGN_SCS_DTM', sa.DateTime(), nullable=True),
    sa.Column('LGN_FLR_TSCNT', sa.Numeric(precision=5), nullable=False),
    sa.Column('LOCK_DSBN_DTM', sa.DateTime(), nullable=True),
    sa.Column('USER_UUID', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['PSTN_DEPT_CD'], ['DEPT_M.DEPT_CD'], ),
    sa.PrimaryKeyConstraint('EMP_NO'),
    sa.UniqueConstraint('EML_ADDR')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EMP_M')
    op.drop_table('DEPT_M')
    op.drop_table('CRTF_TOKN_N')
    op.drop_table('CHTB_SMRY_D')
    op.drop_table('CHTB_MSG_D')
    op.drop_table('ATCH_FILE_M')
    op.drop_table('AGENT_MEM_USE_N')
    op.drop_table('AGENT_M')
    # ### end Alembic commands ###
